### ISSUE TITLE
`matlab_code.m` seems slow

### ISSUE THREAD

**Issue by prclibo** [ZCarofanello/AprilTagsMatlab#1]
Hi, Thumb up for this pure matlab implementation.

I didn't run into detailed code but the `matlab_code.m` runs pretty slow. Each `AprilTag` call takes more than 10s on a 2.6GHz Dual Core i5, which is much slower than your youtube video.  Is this speed expected?

**Comment by ZCarofanello** [comment]
Hi Prclibo,
Without more information about your setup I don't know what the issue would be. Do you have an SSD or HDD? If you disk is slow it might take a while to read the file. Is the system a laptop or a desktop? A laptop might be throttled by power and heat  What version of Matlab are you using? Use 'ver' in the Matlab command window to find out. Maybe you could figure out what the bottle neck might be if you look at these factors.

**Comment by prclibo** [comment]
Thanks for the reply. I am using 2018a. SSD or HDD should not affect the speed so much. I took a look into the code. `CalcEdges` takes ~2s and `MergeEdges` takes ~8s per call of `AprilTag` in `matlab_code.m`. Is this expected?
